http://localhost:8081/api/todos/1

###

POST http://localhost:8081/api/todos/add HTTP/1.1
content-type: application/json

{
    "task": "Cook Dinner",
    "completed": false
}

###

PUT http://localhost:8081/api/todos/1 HTTP/1.1
content-type: application/json

{
    "task": "Cook Dinner",
    "completed": false
}

###

DELETE  http://localhost:8081/api/todos/1 HTTP/1.1


