GET http://localhost:8081/api/todos/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqemFiYTEwIiwiZXhwIjoxNjA3MjI1NTczLCJpYXQiOjE2MDcxODk1NzN9.dIqvP6-fD3IJibJGWVdLgYv7SgvtTYA-rJWBYOxxSUo

###

POST http://localhost:8081/api/todos/add HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqemFiYTEwIiwiZXhwIjoxNjA3MjI1NTczLCJpYXQiOjE2MDcxODk1NzN9.dIqvP6-fD3IJibJGWVdLgYv7SgvtTYA-rJWBYOxxSUo

{
    "task": "Eat Dinner",
    "completed": false
}

###

PUT http://localhost:8081/api/todos/1 HTTP/1.1
content-type: application/json

{
    "task": "Cook Dinner",
    "completed": false
}

###

DELETE  http://localhost:8081/api/todos/1 HTTP/1.1


