
POST http://localhost:8081/api/users/authenticate HTTP/1.1
content-type: application/json

{
    "username": "jzaba10",
    "password": "12345"
}

###

POST http://localhost:8081/api/users/register HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqemFiYTEwIiwiZXhwIjoxNjA3MjI1NTczLCJpYXQiOjE2MDcxODk1NzN9.dIqvP6-fD3IJibJGWVdLgYv7SgvtTYA-rJWBYOxxSUo

{
    "username": "jzaba19",
    "password": "12345"
}